name: Sync

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/source-code-hunter'
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:doocs/source-code-hunter.git
          destination-repo: git@gitee.com:Doocs/source-code-hunter.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: yanglbme
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: doocs/source-code-hunter
          branch: main
